#include<conio.h>
#include<iostream.h>
#include<math.h>
main()
{
float a , b , c,d,X1,X2;
clrscr();
cout<<"ingrese el primer  termino"; cin<<a;cout<<"/n";
cout<<"ingrese el segundo termino"; cin<<b;cout<<"/n";
cout<<"ingrese el tercer  termino"; cin<<c;cout<<"/n";
d=pow(b,2)-4*a*c;
X1=(-b+sqrt(d))/(a*2);
X2=(-b-sqrt(d))/(a*2);
cout<<"/n";
cout<<Las Raices Son:<<"/n";
cout<<X1<<X1<<"/n";
cout<<x2<<x2<<"/n";
getch()
}